// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/smartfx-dashboard/Desktop.tsx": () => import("../components/mockups/smartfx-dashboard/Desktop.tsx"),
  "./components/mockups/smartfx-dashboard/Mobile.tsx": () => import("../components/mockups/smartfx-dashboard/Mobile.tsx"),
  "./components/mockups/smartfx-redesign/DeepSpacePro.tsx": () => import("../components/mockups/smartfx-redesign/DeepSpacePro.tsx"),
  "./components/mockups/smartfx-redesign/NeonMatrix.tsx": () => import("../components/mockups/smartfx-redesign/NeonMatrix.tsx"),
  "./components/mockups/smartfx-redesign/TerminalGold.tsx": () => import("../components/mockups/smartfx-redesign/TerminalGold.tsx")
};
